### ISSUE TITLE
War in Ukraine

### ISSUE THREAD

**Issue by perryaa** [DEADSEC-SECURITY/popcorn-time-api#12]
Since the start of the Ukraine war in 2022, I have not been able to see or connect to the TV shows link ending in .ru-tk shown in the settings. I can do movies since that link is in Mexico. Has the war in Ukraine cutoff the russian link for TV shows? Is there a new link I can insert into the settings for TV shows?

**Comment by DEADSEC-SECURITY** [comment]
Hi @perryaa the current *.tk domain was shutdown by the registar, we are now sending a new update of the API with the new domain. If you would like to overwrite the current domain you can do so by using the `set_base_url` function with the new url being: `https://popcorn-time.ga/`

**Comment by DEADSEC-SECURITY** [comment]
New version released with the new domain as default.
